// Fill out your copyright notice in the Description page of Project Settings.


#include "Projectile.h"
#include "tank.h"
#include "ActorPoolSubsystem.h"
#include "Damageable.h"
#include "GameStructs.h"
#include <Particles/ParticleSystemComponent.h>
#include <Components/AudioComponent.h>

// Sets default values
AProjectile::AProjectile()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.TickInterval = 0.005;


	Mesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mesh"));
	Mesh->SetupAttachment(RootComponent);
	Mesh->OnComponentHit.AddDynamic(this, &AProjectile::OnMeshHit);
	RootComponent = Mesh;

	HitEffect = CreateDefaultSubobject<UParticleSystemComponent>(TEXT("Hit Effect"));
	HitEffect->SetupAttachment(Mesh);

	AudioHitEffect = CreateDefaultSubobject<UAudioComponent>(TEXT("Audio Effect"));
	AudioHitEffect->SetupAttachment(Mesh);

}

void AProjectile::Start()
{
	PrimaryActorTick.SetTickFunctionEnable(true);
	StartPosition = GetActorLocation();
	Mesh->SetHiddenInGame(false);
	Mesh->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
}
// Called when the game starts or when spawned


// Called every frame
void AProjectile::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	FVector NextPosition = GetActorLocation() + GetActorForwardVector() * MoveSpeed * DeltaTime;
	SetActorLocation(NextPosition, true); 
	
	if (FVector::Dist(GetActorLocation(), StartPosition) > FireRange) {
		Stop();
	}
}

void AProjectile::Stop()
{
	PrimaryActorTick.SetTickFunctionEnable(false);
	Mesh->SetHiddenInGame(true);
	Mesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);

	UActorPoolSubsystem* Pool = GetWorld()->GetSubsystem<UActorPoolSubsystem>();
	if (Pool->IsActorInPool(this))
	{
		Pool->ReturnActor(this);
	}
	else
	{
		Destroy();
	}
}

void AProjectile::OnMeshHit(class UPrimitiveComponent* OverlappedComp, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& HitResult)
{
	//UE_LOG(LogTank, Warning, TEXT("Projectile %s collided with %s"), *GetName(), *OtherActor->GetName());

	if (OtherActor == GetInstigator()) {
		Stop();
		return;
	}
	if (OtherComp->IsSimulatingPhysics()) {
		FVector Impulse = Mass * MoveSpeed * GetActorForwardVector();
		OtherComp->AddImpulseAtLocation(Impulse, HitResult.ImpactPoint);

	}
	if (OtherActor && OtherComp && OtherComp->GetCollisionObjectType() == ECC_Destructible) {
		OtherActor->Destroy();
	}
	else if (IDamageable* Damageable = Cast<IDamageable>(OtherActor)) {
		FDamageData DamageData;
		DamageData.DamageValue = Damage;
		DamageData.Instigator = GetInstigator();
		DamageData.DamageMaker = this;
		Damageable->DamageTake(DamageData);
		HitEffect->Activate();
		AudioHitEffect->Play();
	}
	Stop();
}

